spring.application.name=fsd
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB	
server.tomcat.connection-timeout=60000
server.tomcat.keep-alive-timeout=60000
server.tomcat.max-swallow-size=-1
spring.servlet.multipart.file-size-threshold=2KB
testlink.username=mjadhav
testlink.devkey=584c2e1e2e0c0a09122f285199f8904a
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger - %msg%n